### ISSUE TITLE
Letswave FFT filter error when dataset length is odd.

### ISSUE THREAD

**Issue by ZZzeal** [NOCIONS/letswave7#13]
## File letswave7-master\LW_Core\CLW_buildFFTfilter.m
![letswave_q1](https://user-images.githubusercontent.com/19574652/127727251-c71703e8-b04c-45cb-b30f-465eebde054a.png)
![letswave_q2](https://user-images.githubusercontent.com/19574652/127727252-674d3221-850a-4855-8143-b3bb0d8d9005.png)
## Modification suggestions
change to:
Line 36: v((end+1)/2+1:end)=v((end-1)/2:-1:1);

**Comment by ArCourtin** [comment]
I experienced this problem just now.
I fixed it that way:
 Line 36:    v((end+1)/2:end)=v(2+(end-1)/2:-1:2);
